package com.eventify.serviceImpl;

import java.io.StringWriter;

import org.apache.velocity.VelocityContext;
import org.apache.velocity.app.VelocityEngine;

public class EmailTemplateRenderer {
	private static final String TEMPLATE_CONTENT = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"utf-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "    <title>Return more info</title>\r\n"
			+ "    <style>\r\n"
			+ "        body {\r\n"
			+ "            font-family: 'Poppins', sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        table {\r\n"
			+ "            width: 60%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        td {\r\n"
			+ "            padding: 20px;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .container {\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            background-color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section img {\r\n"
			+ "            max-width: 60%;\r\n"
			+ "            margin: 0 auto;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section {\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section h1 {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            line-height: 1.5;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .colored-text {\r\n"
			+ "            color: #078A9B;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .name {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .main-para {\r\n"
			+ "            font-size: 1rem;\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-weight: 500;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button {\r\n"
			+ "            border: none;\r\n"
			+ "            background-color: #189D91;\r\n"
			+ "            padding: 0.8rem 2rem;\r\n"
			+ "            color: #FFF;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            display: inline-block;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button:hover {\r\n"
			+ "            background-color: #71bbb5;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .sec-para {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            color: #494949;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h1 {\r\n"
			+ "            color: #0896A9;\r\n"
			+ "            font-size: 1.6rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h3 {\r\n"
			+ "            font-size: 1.4rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .contact-info img {\r\n"
			+ "            max-width: 30px;\r\n"
			+ "            margin-left: 42%;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            align-items: center;\r\n"
			+ "        }\r\n"
			+ "        .contact-info div {\r\n"
			+ "            display: flex;\r\n"
			+ "            align-items: center;\r\n"
			+ "            margin-bottom: 10px; /* Adjust margin as needed */\r\n"
			+ "            margin: auto;\r\n"
			+ "            width: 100%;\r\n"
			+ "        }\r\n"
			+ "        \r\n"
			+ "\r\n"
			+ "        .footer {\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding-top: 4rem;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <table role=\"presentation\" class=\"container\">\r\n"
			+ "        <tr>\r\n"
			+ "            <td>\r\n"
			+ "                <div class=\"top-section\">\r\n"
			+ "                    <img class=\"img-responsive\" src=\"https://g2s.blob.core.windows.net/images/mail.png\" alt=\"\">\r\n"
			+ "                    <div class=\"pt-5\">\r\n"
			+ "                        <h1>Return Requested</h1>\r\n"
			+ "                        <p class=\"colored-text\">Your Return ${RMA_QUALIFIER} ${RMA_NO} has been Requested</p>\r\n"
			+ "                        <p class=\"name\">Hi \"${CUST_NAME}\"</p>\r\n"
			+ "                        <p class=\"main-para\">We're happy to let you know that your Return has been Requested. We will\r\n"
			+ "                            be in\r\n"
			+ "                            touch shortly with an update on your status.</p>\r\n"
			+ "                        <p class=\"sec-para\">Your return reference number is: ${RMA_QUALIFIER} ${RMA_NO} Please keep this\r\n"
			+ "                            number for your\r\n"
			+ "                            records.</p>\r\n"
			+ "                        <p class=\"main-para\">If you would like to see your return status and other returns, please login\r\n"
			+ "                            to\r\n"
			+ "                            <a href=\"http://tld.gocontinuum.ai/\">tld.gocontinuum.ai</a>\r\n"
			+ "                        </p>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "\r\n"
			+ "                <div class=\"bottom-section\">\r\n"
			+ "                    <h1>Got a question?</h1>\r\n"
			+ "                    <h3>We're here to help you</h3>\r\n"
			+ "                    <div class=\"contact-info\">\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-mail.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_MAIL}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-phone.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_PHONE}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "            </td>\r\n"
			+ "        </tr>\r\n"
			+ "    </table>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>\r\n"
			+ "";
	
	public String getTemplateContent() {
		return TEMPLATE_CONTENT;
	}
	
	public static String renderer(String template, VelocityContext context) {
		VelocityEngine velocityEngine = new VelocityEngine();
		velocityEngine.init();

		try {
			StringWriter writer = new StringWriter();
			velocityEngine.evaluate(context, writer, "EmailTemplate", template);
			return writer.toString();
		} catch (Exception ex) {
			ex.printStackTrace();
		}

		return null;
	}
}
